import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation"; // Import the Navigation component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add head content here if needed */}
      </head>
      <body className={inter.className}>
        <Navigation /> {/* Include the Navigation component */}
        {children}
        <footer>
          {/* Footer content goes here */}
          <p>© 2024 Kids Trivia Game. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
